# Generated by Django 5.0.4 on 2024-04-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='body',
            field=models.TextField(default='This field is missing...'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='color',
            field=models.CharField(default='Blue', max_length=20),
        ),
    ]
